resources:
- name: git-import-repo
  type: git
  source:
    uri: git@github.com:zapatacomputing/git-import.git
    branch: master
    private_key: ((zapatabot-ssh))
- name: git-import-builds
  type: s3
  source:
    bucket: zapata-cicd-development-packages
    regexp: git-import/build-(.*).tgz
    access_key_id: ((development-package-storage-aws-access-key-id))
    secret_access_key: ((development-package-storage-aws-secret-access-key))
- name: git-import-prerelease
  type: github-release
  source:
    owner: zapatacomputing
    repository: git-import
    release: false
    pre_release: true
    access_token: ((zapatabot-github-access-token))
    tag_filter: ^\w+.(\w+\.\w+)
- name: git-import-release
  type: github-release
  source:
    owner: zapatacomputing
    repository: git-import
    release: true
    pre_release: false
    access_token: ((zapatabot-github-access-token))
    tag_filter: ^\w+.(\w+\.\w+)
jobs:
# Trigger Build
- name: run-tests
  serial: true
  plan:
  - get: git-import-repo
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: zapatacomputing/cicd
          tag: latest
      params:
        ZAPATABOT_SSH: ((zapatabot-ssh))
      inputs:
      - name: git-import-repo
        path: git-import
      run:
        path: git-import/ci_cd/test.sh
- name: build-to-s3
  serial: true
  plan:
  - get: git-import-repo
    passed: [run-tests]
    trigger: true
  - task: build-binaries
    params:
      STAR_VERSION: sirius
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: 1.16
      inputs:
      - name: git-import-repo
        path: git-import
      outputs:
      - name: release-artifacts
      run:
        path: git-import/ci_cd/build.sh
  - put: git-import-builds
    params:
        file: release-artifacts/build-*.tgz
# Promote Build to Pre-Release
- name: promote-s3-build-to-github-prerelease
  plan:
  - get: git-import-builds
    passed: [build-to-s3]
    params:
      unpack: true
  - put: git-import-prerelease
    params:
      name: git-import-builds/version
      tag: git-import-builds/version
      commitish: git-import-builds/commit_sha
      globs:
      - git-import-builds/git-import-*
# Promote Pre-Release to Release
- name: promote-github-prerelease-to-release
  plan:
  - get: git-import-prerelease
  - put: git-import-release
    params:
      name: git-import-prerelease/tag
      tag: git-import-prerelease/tag
      commitish: git-import-prerelease/commit_sha
      globs:
      - git-import-prerelease/git-import-*

groups:
  - name: build
    jobs:
      - run-tests
      - build-to-s3
  - name: promotion
    jobs:
     - promote-s3-build-to-github-prerelease
     - promote-github-prerelease-to-release