resources:
- name: git-import-repo
  type: git
  source:
    uri: git@github.com:zapatacomputing/git-import.git
    branch: master
    private_key: ((zapatabot-ssh))
- name: git-import-builds
  type: s3
  source:
    bucket: zapata-cicd-development-packages
    regexp: git-import/build-(.*).tgz
    access_key_id: ((development-package-storage-aws-access-key-id))
    secret_access_key: ((development-package-storage-aws-secret-access-key))
- name: git-import-prerelease
  type: s3
  source:
    bucket: zapata-cicd-stage-packages
    regexp: git-import/build-(.*).tgz
    access_key_id: ((development-package-storage-aws-access-key-id))
    secret_access_key: ((development-package-storage-aws-secret-access-key))
- name: git-import-release
  type: s3
  source:
    bucket: zapata-cicd-production-packages
    regexp: git-import/build-(.*).tgz
    access_key_id: ((development-package-storage-aws-access-key-id))
    secret_access_key: ((development-package-storage-aws-secret-access-key))
jobs:
# Trigger Build
- name: run-tests
  serial: true
  plan:
  - get: git-import-repo
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: zapatacomputing/cicd
          tag: latest
      params:
        ZAPATABOT_SSH: ((zapatabot-ssh))
      inputs:
      - name: git-import-repo
        path: git-import
      run:
        path: git-import/ci_cd/test.sh
- name: build-to-s3
  serial: true
  plan:
  - get: git-import-repo
    passed: [run-tests]
    trigger: true
  - task: build-binaries
    params:
      STAR_VERSION: sirius
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: 1.16
      inputs:
      - name: git-import-repo
        path: git-import
      outputs:
      - name: release-artifacts
      run:
        path: git-import/ci_cd/build.sh
  - put: git-import-builds
    params:
        file: release-artifacts/build-*.tgz
# Publish git-import to docs.orquestra site
- name: publish-testing
  serial: true
  plan:
  - get: git-import-builds
    trigger: true
    passed: [build-to-s3]
    params:
      unpack: true
  - task: deploy-to-docs-orquestra-wtf
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: zapatacomputing/cicd
          tag: latest
          username: ((zapatabot-dockerhub-username))
          password: ((zapatabot-dockerhub-password))
      params:
        S3_BUCKET: zap-website-docs.orquestra.wtf
        AWS_ACCESS_KEY_ID: ((aws-zapata-docs-orquestra-wtf-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-zapata-docs-orquestra-wtf-secret-access-key))
        AWS_DEFAULT_REGION: 'us-east-1'
      inputs:
        - name: git-import-builds
          path: git-import
      run:
        path: bash
        args: [-c, 'echo "cd git-import && mkdir -p import/bin/ && ls -la && cp git-import-* import/bin/ && aws s3 sync --sse AES256 import s3://${S3_BUCKET}/import/" > s3.sh && chmod +x s3.sh && ./s3.sh']
- name: publish-production
  serial: true
  plan:
  - get: git-import-release
    params:
      unpack: true
  - task: deploy-to-docs-orquestra-io
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: zapatacomputing/cicd
          tag: latest
          username: ((zapatabot-dockerhub-username))
          password: ((zapatabot-dockerhub-password))
      params:
        S3_BUCKET: zap-website-docs.orquestra.io
        AWS_ACCESS_KEY_ID: ((aws-zapata-docs-orquestra-io-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-zapata-docs-orquestra-io-secret-access-key))
        AWS_DEFAULT_REGION: 'us-east-1'
      inputs:
        - name: git-import-release
          path: git-import
      run:
        path: bash
        args: [-c, 'echo "cd git-import && mkdir -p import/bin/ && ls -la && cp git-import-* import/bin/ && aws s3 sync --sse AES256 import s3://${S3_BUCKET}/import/" > s3.sh && chmod +x s3.sh && ./s3.sh']
# Promote Build to Pre-Release
- name: promote-s3-build-to-github-prerelease
  plan:
  - get: git-import-builds
    passed: [build-to-s3]
  - put: git-import-prerelease
    params:
      file: git-import-builds/*.tgz
      acl: private
# Promote Pre-Release to Release
- name: promote-github-prerelease-to-release
  plan:
  - get: git-import-prerelease
  - put: git-import-release
    params:
      file: git-import-prerelease/*.tgz
      acl: private

groups:
  - name: build
    jobs:
      - run-tests
      - build-to-s3
  - name: deploy
    jobs:
      - publish-testing
      - publish-production
  - name: promotion
    jobs:
     - promote-s3-build-to-github-prerelease
     - promote-github-prerelease-to-release